Updating the scripts
bridgedb/create-bridgedb-genedb pull request #26
Opened 2022-08-11 16:16 UTC by tabbassidaloii

The schema is updated from GdbConstructImpl3 to GdbConstructImpl4 (DbBuilder.java).
In the previous version, user should modify BioMart2Bdb.java and add DATASOURCENAME and VERSION. In this version, user should provide them as arguments meaning that instead of two mandatory arguments (<configFile> and <outputPath>), one should provide four arguments:

```
java -jar BioMart2BridgeDb.jar <DATASOURCENAME> <VERSION> <configFile> <outputPath> <oldDB> <inclusive>
```
I will update the README.md file if you agree with these changes.

2022-08-12 19:22 UTC, egonw requested changes
Small comment (hahaha).

2022-08-12 19:22 UTC, egonw commented on src/main/java/org/bridgedb/creator/EnsemblREST.java
> +		String DATASOURCENAME = args[0];
Java convention is to use here `datasourceName`

2022-08-12 19:22 UTC, egonw commented on src/main/java/org/bridgedb/creator/Main.java
> +		String DATASOURCENAME = null;
See earlier comment about `datasourceName`

2022-08-15 07:50 UTC, tabbassidaloii commented
> Small comment (hahaha). Otherwise looks great!

Fixed :)

2022-08-25 12:30 UTC, merged